package com.luciano.cadastropessoa.cadastrarpessoa.exception

class BookNotFoundException(id: Long): RuntimeException("N√ÉO EXISTE ESSE ID TESTE ERRO: $id")